[package]
name = "fuzz-util"
version = "0.0.0"
edition = "2021"

[dependencies]

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    #
    'cfg(kani)',
    'cfg(no)',
    'cfg(fuzzing)',
    'cfg(prop)',
    'cfg(rust_analyzer)',
]
